version: 2.1

jobs:  
  build-docs:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Build docs
          command: cd docs/ && make html -W --keep-going
      - persist_to_workspace:
          root: docs/_build
          paths: html
    
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Disable jekyll builds
          command: touch docs/_build/html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "seh33@uw.edu"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "9d:0d:87:cc:12:31:d5:10:99:c9:dc:5d:3a:fd:cd:b1"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html

workflows:
  version: 2
  test:
    jobs:
      - build-docs
      - docs-deploy:
          requires:
            - build-docs
          filters:
            branches:
              only: main