name: Build Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Replace with the Python version you need

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Adjust the path as needed

      - name: Build Documentation
        run: |
          cd docs  # The directory containing your Sphinx documentation
          make html  # Your Sphinx build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: docs/_build/html
